### PR TITLE
Added some flexibility regarding the query which is passed to the component. 

### PR DESCRIPTION
**Pull request by ghost**
I was having trouble getting the graphql to output the data in the format which satisfied the plugin so I altered it in order to some flexibility to it. The function created will allow you to simply search for the fluid element of each node passed to the component. Then you simply pass that fluid element to the Image component. 

- Lines 57 - 67: A simple function which takes two arguments -- an object (haystack) and a string (needle).
It will recursively check to see if it can find a key/value pair which matches the needle and return the matching object if it finds one or null if not.

- Line 94: Pass the data object to the findObject function with a needle of fluid

### CODE REVIEW

**Comment by GabeEddyT** [comment]
Sorry for getting to this so late. Would you mind providing an example of the graphql query/file-structure you're testing with?

**Comment by GabeEddyT** [comment]
Modifying `findObject` to match [this snippet](https://stackoverflow.com/a/40604638), worked for me, but I'd still like to know where you were having issues with `fluid` not being found.

```js
const findObject = (haystack, needle) => {
  var value;
  Object.keys(haystack).some(function (k) {
    if (k === needle) {
      value = haystack[k];
      return true;
    }
    if (haystack[k] && typeof haystack[k] === 'object') {
      value = findObject(haystack[k], needle);
      return value !== undefined;
    }
  });
  return value;
};
```

**Comment by MakingStuffs** [comment]
> Modifying `findObject` to match [this snippet](https://stackoverflow.com/a/40604638), worked for me, but I'd still like to know where you were having issues with `fluid` not being found.
> 
> ```js
> const findObject = (haystack, needle) => {
>   var value;
>   Object.keys(haystack).some(function (k) {
>     if (k === needle) {
>       value = haystack[k];
>       return true;
>     }
>     if (haystack[k] && typeof haystack[k] === 'object') {
>       value = findObject(haystack[k], needle);
>       return value !== undefined;
>     }
>   });
>   return value;
> };
> ```

Nice one mate, I did not know about the `some()` function! Seems like a simpler way to do what I was trying to do for sure. Although, out of curiosity, did my solution work for you also? 

The query I was passing to the props was as follows:
```
useStaticQuery(graphql`
    query {
      backgrounds: allStrapiHeaderImages {
        nodes {
          image {
            childImageSharp {
              fluid(quality: 90, maxWidth: 1920) {
                ...GatsbyImageSharpFluid_withWebp_tracedSVG
              }
            }
          }
        }
      }
    }
  `)
```
As you can see, the issue was in the fact that the images were stored under the `image` key. I am sure there is probably some way to make grapQL remove the parent but I could not find it.

**Comment by GabeEddyT** [comment]
Your original solution didn't work for me. The structure of the query I use mirrors the one in the Readme:

```graphql
query {
	backgrounds: allFile (filter: {sourceInstanceName: {eq: "backgrounds"}}){
		nodes {
			relativePath
			childImageSharp {
				fluid (maxWidth: 4000, quality: 100){
					...GatsbyImageSharpFluid_withWebp_tracedSVG
				}
			}
		}
	}
}
```

So I'm not sure why your function wouldn't work unless it requires an extra level of depth.

Can you confirm that the solution I pulled from StackOverflow works with your setup?

**Pull request closed without merging**
